apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: "2025-06-03T09:04:30Z"
  generation: 18
  name: jupyter-nb-kube-3aadmin
  namespace: rhods-notebooks
  ownerReferences:
  - apiVersion: kubeflow.org/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: Notebook
    name: jupyter-nb-kube-3aadmin
    uid: daf61b40-d667-4ea2-aaa0-c160ae8fafe6
  resourceVersion: "492408"
  uid: 7d877632-7847-4a3e-a576-158c172fae38
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      statefulset: jupyter-nb-kube-3aadmin
  serviceName: ""
  template:
    metadata:
      annotations:
        kubeflow-resource-stopped: odh-notebook-controller-lock
        opendatahub.io/accelerator-name: ""
        opendatahub.io/hardware-profile-name: ""
        opendatahub.io/username: kube:admin
      creationTimestamp: null
      labels:
        app: jupyter-nb-kube-3aadmin
        notebook-name: jupyter-nb-kube-3aadmin
        opendatahub.io/dashboard: "true"
        opendatahub.io/odh-managed: "true"
        opendatahub.io/user: kube-3aadmin
        opendatahub.io/workbenches: "true"
        statefulset: jupyter-nb-kube-3aadmin
    spec:
      containers:
      - env:
        - name: NOTEBOOK_ARGS
          value: |-
            --ServerApp.port=8888
                              --ServerApp.token=''
                              --ServerApp.password=''
                              --ServerApp.base_url=/notebook/rhods-notebooks/jupyter-nb-kube-3aadmin
                              --ServerApp.quit_button=False
                              --ServerApp.tornado_settings={"user":"kube-3aadmin","hub_host":"https://rhods-dashboard-redhat-ods-applications.apps.ocpz-standard-2.t313lp74.lnxero1.boe","hub_prefix":"/notebookController/kube-3aadmin"}
        - name: JUPYTER_IMAGE
          value: jupyter-minimal-notebook:2024.2
        - name: JUPYTER_NOTEBOOK_PORT
          value: "8888"
        - name: PIP_CERT
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: REQUESTS_CA_BUNDLE
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: SSL_CERT_FILE
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: PIPELINES_SSL_SA_CERTS
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: GIT_SSL_CAINFO
          value: /etc/pki/tls/custom-certs/ca-bundle.crt
        - name: NB_PREFIX
          value: /notebook/rhods-notebooks/jupyter-nb-kube-3aadmin
        image: quay.io/ayshamk/notebook@sha256:28d954f5fc3f0a22d56034e9da38b9fbb9afc1d648630734ada4d8f8ae4d59bb
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /notebook/rhods-notebooks/jupyter-nb-kube-3aadmin/api
            port: notebook-port
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: jupyter-nb-kube-3aadmin
        ports:
        - containerPort: 8888
          name: notebook-port
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /notebook/rhods-notebooks/jupyter-nb-kube-3aadmin/api
            port: notebook-port
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "2"
            memory: 8Gi
          requests:
            cpu: "1"
            memory: 8Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/app-root/src
          name: jupyterhub-nb-kube-3aadmin-pvc
        - mountPath: /dev/shm
          name: shm
        - mountPath: /etc/pki/tls/custom-certs/ca-bundle.crt
          name: trusted-ca
          readOnly: true
          subPath: ca-bundle.crt
        - mountPath: /opt/app-root/pipeline-runtimes/
          name: runtime-images
        workingDir: /opt/app-root/src
      - args:
        - --provider=openshift
        - --https-address=:8443
        - --http-address=
        - --openshift-service-account=jupyter-nb-kube-3aadmin
        - --cookie-secret-file=/etc/oauth/config/cookie_secret
        - --cookie-expire=24h0m0s
        - --tls-cert=/etc/tls/private/tls.crt
        - --tls-key=/etc/tls/private/tls.key
        - --upstream=http://localhost:8888
        - --upstream-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        - --email-domain=*
        - --skip-provider-button
        - --client-id=jupyter-nb-kube-3aadmin-rhods-notebooks-oauth-client
        - --client-secret-file=/etc/oauth/client/secret
        - --scope=user:info user:check-access
        - --openshift-sar={"verb":"get","resource":"notebooks","resourceAPIGroup":"kubeflow.org","resourceName":"jupyter-nb-kube-3aadmin","namespace":"$(NAMESPACE)"}
        - --logout-url=https://rhods-dashboard-redhat-ods-applications.apps.ocpz-standard-2.t313lp74.lnxero1.boe/notebookController/kube-3aadmin/home
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: registry.redhat.io/openshift4/ose-oauth-proxy@sha256:4f8d66597feeb32bb18699326029f9a71a5aca4a57679d636b876377c2e95695
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /oauth/healthz
            port: oauth-proxy
            scheme: HTTPS
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: oauth-proxy
        ports:
        - containerPort: 8443
          name: oauth-proxy
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /oauth/healthz
            port: oauth-proxy
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 100m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/oauth/client
          name: oauth-client
        - mountPath: /etc/oauth/config
          name: oauth-config
        - mountPath: /etc/tls/private
          name: tls-certificates
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: jupyter-nb-kube-3aadmin
      serviceAccountName: jupyter-nb-kube-3aadmin
      terminationGracePeriodSeconds: 30
      volumes:
      - name: jupyterhub-nb-kube-3aadmin-pvc
        persistentVolumeClaim:
          claimName: jupyterhub-nb-kube-3aadmin-pvc
      - emptyDir:
          medium: Memory
        name: shm
      - configMap:
          defaultMode: 420
          items:
          - key: ca-bundle.crt
            path: ca-bundle.crt
          name: workbench-trusted-ca-bundle
          optional: true
        name: trusted-ca
      - name: oauth-config
        secret:
          defaultMode: 420
          secretName: jupyter-nb-kube-3aadmin-oauth-config
      - name: oauth-client
        secret:
          defaultMode: 420
          secretName: jupyter-nb-kube-3aadmin-oauth-client
      - name: tls-certificates
        secret:
          defaultMode: 420
          secretName: jupyter-nb-kube-3aadmin-tls
      - configMap:
          defaultMode: 420
          name: pipeline-runtime-images
          optional: true
        name: runtime-images
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
status:
  availableReplicas: 0
  collisionCount: 0
  currentReplicas: 1
  currentRevision: jupyter-nb-kube-3aadmin-c64476f85
  observedGeneration: 18
  replicas: 1
  updateRevision: jupyter-nb-kube-3aadmin-c64476f85
  updatedReplicas: 1
